### ISSUE TITLE
BUG - Management Web-Client Glitch

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#112]
**Describe the bug**
The Management Web Client session expires whilst one is using the app. I know that after I find the "Orders" or "Featured Posts" windows are blank. Upon refreshing the page, all I get to see in one option in the Nav. Please refer to the screenshot attached. 

**To Reproduce**
1. Go to "localhost:5202"
2. Log in with SUPERADMIN credentials
3. Try editing a product or adding a new one or do anything on the platform
4. All of a sudden, your session will expire.

**Expected behavior**
The session should not expire whilst a user is doing something. It should expire if the window has been ideal for sometime.

**Screenshots**
<img width="1241" alt="Screenshot 2020-05-08 at 12 30 28 PM" src="https://user-images.githubusercontent.com/23535062/81381521-7e30c200-912a-11ea-89d9-c86f8c68c779.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest Stable

**Comment by smaharj1** [comment]
I wasn't able to reproduce this issue. One issue might be that you are trying to edit the existing products. Currently, editing products depend on S3. Since we aren't allowing the local environment to S3, please try it with new products.

**Comment by gfyre** [comment]
Hey @smaharj1 I'll try setting up my own S3 and then reopen this thread if the issue still persists. Thanks.
