### ISSUE TITLE
Unable to Delete a category

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#113]
How do I delete a category or a sub category of a product?

When I try to click on "edit" and just erase the names out, I see the following in my console

<img width="1267" alt="Screenshot 2020-05-08 at 12 40 55 PM" src="https://user-images.githubusercontent.com/23535062/81381798-e8e1fd80-912a-11ea-8cef-41cfde46b202.png">

From this I understand that I cannot leave the text boxes blank.

**Comment by gfyre** [comment]
Also, when I do add a new category, why doesn't it show up on the home page nav bar (at the top)?

**Comment by Viveckh** [comment]
- Categories and Subcategories cannot be deleted. You can rename them, but not delete them. It was set up this way to prevent a cascade of null references that might result in products and orders collection where deleted categories are referenced.

- The categories on the top menubar aren't dynamically set and don't render every possible category. It is up to the implementer to override which categories to display there, as per their use case. However, on the catalog page, the categories should appear dynamically once added.

**Comment by gfyre** [comment]
@Viveckh Understood. Thanks for the clarifications. I am now closing this issue.
