### ISSUE TITLE
getting error during installation

### ISSUE THREAD

**Issue by deepakfordeep** [Viveckh/Veniqa#121]
Hello
I am trying to install in local but getting error on shopping-server
E:\veniqa\shopping-server\node_modules\winston-mongodb\lib\winston-mongodb.js:55
    throw new Error('You should provide db to log to.');
Screenshot is here : http://prntscr.com/sqm6ad
Please guide

**Comment by gfyre** [comment]
The error essentially states that it isn't able to find or connect to your database

You need to make sure of the following things:-

1. The `env.developement` or `env.production` files are filed as outlined in the  [env.format](https://github.com/Viveckh/Veniqa/blob/develop/shopping-server/.env.format)

2. Your mongo db instance (local or on cloud) is actually running

3. Your mongo db credentials are correct

**Comment by smaharj1** [comment]
I believe this has been resolved.
