### ISSUE TITLE
Re-routing to last open URL upon login

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#125]
**Describe the bug**
When clicking on "Login" after clicking on "Add to cart", post logging in, the user is redirected to the home page
**To Reproduce**
1. Go to any product (without signing in0
2. Click on "Add to Cart" and then login by clicking the button on the prompt
3. Login with your credentials
4. You will then be redirected to the login page

**Expected behavior**

The user should not be redirected to the login page and the product should be added to their cart post a successful login/signup.

**Comment by AmandaDLyon** [comment]
I was going to report this very bug @gfyre !

@Viveckh is there a reason why this happens?

**Comment by smaharj1** [comment]
Right now, we are not tracking the history of the last open URL. It would be a cool feature though.
