### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#126]
**Describe the bug**
Some minor alignment issues

**To Reproduce**

Refer to the screenshots

**Expected behavior**

The "Order Details" should be fully visible (in the first image) and the product images along with the Veniqa logo must be aligned to the centre of the screen (in the second image)

**Screenshots**

<img width="271" alt="Screenshot 2020-06-22 at 1 24 04 PM" src="https://user-images.githubusercontent.com/23535062/85262750-d7ab4100-b48b-11ea-923e-201feccb20e4.png">

<img width="268" alt="Screenshot 2020-06-22 at 1 23 46 PM" src="https://user-images.githubusercontent.com/23535062/85262742-d4b05080-b48b-11ea-8f91-a5706c83c3f0.png">

**Comment by smaharj1** [comment]
Thanks for bringing this to attention
