### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#128]
**Describe the bug**
After adding a new address and clicking on save, the text fields are still there. Also, (a rather minute one), the "save" and "cancel" button aren't aligned.

**To Reproduce**
1. On the checkout page, try adding a new address or editing an existing one
2. Click on Save
3. The text boxes are still present at the bottom.
4. And while you are there, look at the "Cancel" and "Save" button. They aren't aligned.

**Expected behavior**
After adding a new address and clicking on save, the text fields should go away and the alignment of the "Cancel" and "Save" button must be besides each other and not variable.

**Screenshots**
<img width="584" alt="Screenshot 2020-06-24 at 3 02 45 PM" src="https://user-images.githubusercontent.com/23535062/85537699-d156c980-b631-11ea-9972-ba76b80a9dff.png">

<img width="572" alt="Screenshot 2020-06-24 at 3 02 10 PM" src="https://user-images.githubusercontent.com/23535062/85537693-cf8d0600-b631-11ea-8add-3f0926767a24.png">

@smaharj1 This one seems to be for you ;) Thanks for being so swift with the changes.

**Comment by gfyre** [comment]
@smaharj1 @Viveckh any updates on this?

**Comment by smaharj1** [comment]
Let me try to get this done this weekend.
