### ISSUE TITLE
Order Recieved Email

### ISSUE THREAD

**Issue by AmandaDLyon** [Viveckh/Veniqa#137]
Hey, can you guys share your sendgrid template for an Order Recieved email. I cant seem to get the email to display the order information properly. 

What I want is the code you have placed inside of Sendgrid's dynamic template. @smaharj1 @Viveckh 

Cheers!

**Comment by Viveckh** [comment]
Hi @AmandaDLyon, sorry about the delay. The SendGrid email templates are now available on the `setup-resources/sendgrid_email_templates` folder. Accompanying documentation on how to go about using it, along with how to implement a different email service provider is also now available on the [documentation site.](https://documentation.veniqa.com/email-setup/email-setup.html)
