### ISSUE TITLE
how to debug management-server

### ISSUE THREAD

**Issue by myminseok** [Viveckh/Veniqa#90]
Hi, I am new on this.
I would like to debug 'management-server' logs, but not much logs on stdout.
could you please let me know how to print out debug logs to stdout?
I would like to debug what causes errors when login admin to management-server.

**Comment by Viveckh** [comment]
Hi there,
The logs are all piped to files in `/logging/logs` folder.
Additionally, the error logs are also stored in the MongoDB database.
You can configure the file names and collection name in the [config files here.](https://github.com/Viveckh/Veniqa/tree/develop/management-server/config)

Also, you can modify the default logging behavior if you want to see everything in the console by modifying [this logger module.](https://github.com/Viveckh/Veniqa/blob/develop/management-server/logging/logger.js)
